from typing import Any
from collections.abc import Generator

import numpy as np
from numpy.typing import NDArray as NDArray

from ..console import console as console

_DEFAULT_SCALAR_DTYPE: np.dtype[Any]

def ensure_list(input_item: Any) -> list[Any]: ...
def chunk_iterable(
    iterable: NDArray[Any] | tuple[Any, ...] | list[Any], chunk_size: int
) -> Generator[tuple[Any, ...] | NDArray[Any], None, None]: ...
def error_format(message: str) -> str: ...
def resolve_worker_count(requested_workers: int = 0, reserved_cores: int = 2) -> int: ...
def resolve_parallel_job_capacity(workers_per_job: int) -> int: ...
def convert_scalar_to_bytes(
    value: int | float | bool | np.generic, dtype: np.dtype[Any] = ...
) -> NDArray[np.uint8]: ...
def convert_bytes_to_scalar(data: NDArray[np.uint8], dtype: np.dtype[Any] = ...) -> int | float | bool: ...
def convert_array_to_bytes(array: NDArray[Any]) -> NDArray[np.uint8]: ...
def convert_bytes_to_array(data: NDArray[np.uint8], dtype: np.dtype[Any]) -> NDArray[Any]: ...
def _cached_convert_scalar_to_bytes(value: int | float | bool, dtype_str: str) -> bytes: ...
